const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
process.env.PW_TEST_SCREENSHOT_NO_FONTS_READY='1';
(async()=>{
  const browser=await chromium.launch({channel:'msedge',headless:true});
  try {
    const page=await browser.newPage({viewport:{width:1180,height:820},hasTouch:true});
    const errors=[];page.on('pageerror',e=>errors.push(e.message));
    await page.goto('http://localhost:3020/assets/games/mudline/index.html');
    await page.waitForTimeout(1200);
    console.log('Vehicle spawned');
    const initial=await page.evaluate(()=>mudline.state().x);
    await page.keyboard.down('ArrowRight');await page.waitForTimeout(3500);await page.keyboard.up('ArrowRight');
    const after=await page.evaluate(()=>mudline.state());console.log('After gas',{x:after.x,y:after.y,speed:after.speed,angle:after.angle});
    assert.ok(after.x>initial+30,'Gas moves the vehicle');
    await page.screenshot({path:path.join(os.tmpdir(),'mudline-drive.png')});
    await page.getByRole('button',{name:'Garage',exact:true}).click();
    await page.locator('[data-vehicle="tidal"]').click();
    await page.locator('[data-tune="power"]').fill('165');
    await page.locator('#assist').uncheck();
    await page.screenshot({path:path.join(os.tmpdir(),'mudline-garage.png')});
    await page.locator('#applyTune').click();
    assert.equal(await page.evaluate(()=>mudline.state().vehicle),'tidal');
    assert.equal(await page.evaluate(()=>mudline.state().tune.power),165);
    await page.getByRole('button',{name:'Map creator',exact:true}).click();
    await page.locator('#mapName').fill('Test pond park');await page.locator('#beginEdit').click();
    await page.locator('#brush').selectOption('water');
    await page.mouse.move(600,430);await page.mouse.down();await page.mouse.move(760,440,{steps:10});await page.mouse.up();
    assert.ok((await page.evaluate(()=>mudline.state().surfaces)).includes('water'));
    await page.locator('#saveMap').click();await page.locator('#testMap').click();
    assert.equal(await page.evaluate(()=>mudline.state().savedMaps),1);
    await page.reload();assert.equal(await page.evaluate(()=>mudline.state().savedMaps),1);
    await page.getByRole('button',{name:'Maps',exact:true}).click();await page.locator('[data-map="dunes"]').click();
    await page.setViewportSize({width:390,height:844});await page.waitForTimeout(300);
    await page.screenshot({path:path.join(os.tmpdir(),'mudline-mobile.png')});
    const gasBox=await page.locator('[data-control="gas"]').boundingBox();assert.ok(gasBox.x>=0&&gasBox.x+gasBox.width<=390);
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),390);
    const wheelieBox=await page.locator('[data-control="wheelie"]').boundingBox();
    const cdp=await page.context().newCDPSession(page);
    const touchStart=await page.evaluate(()=>mudline.state().x);
    await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:gasBox.x+gasBox.width/2,y:gasBox.y+gasBox.height/2,id:0},{x:wheelieBox.x+wheelieBox.width/2,y:wheelieBox.y+wheelieBox.height/2,id:1}]});
    await page.waitForTimeout(900);
    assert.ok(await page.evaluate(()=>mudline.state().x)>touchStart+20,'Two-finger gas and wheelie controls drive the vehicle');
    await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
    const cover=await page.evaluate(()=>{const c=document.createElement('canvas');mudline.thumbnail(c,mudline.vehicles[0]);return c.toDataURL('image/png').split(',')[1];});
    fs.writeFileSync(path.join(__dirname,'../assets/games/mudline/cover.png'),Buffer.from(cover,'base64'));
    assert.deepEqual(errors,[]);console.log('Driving, tuning, map painting/save/reload and mobile layout passed.');
  }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
